server/src/controllers/tattooArtistControllers/createTattooArtist.js, server/src/controllers/tattooArtistControllers/updateTattooArtist.js, server/src/handlers/tattooArtistHandlers/createTattooArtistHandler.js, server/src/handlers/tattooArtistHandlers/updateTattooArtistHandler.js, server/src/routes/tattooArtistRouter.js
Agregué el método put al crud del tatuador
=> Crud tattoo artist

client/src/components/filterSideBar/FilterSideBar.jsx, server/src/handlers/filterHandlers/getTattooArtistFilteredHandler.js, server/src/routes/filterRouter.js
creo esta ruta en base a la de filtros de connie para no sobreescribir porque vi que habia varias cosas mas con respecto al devep, estuve probando y la info llega de la manera correcta, cambie get por post  en back y en front cambie la logica para que se almacene en array tattoostyle y el otro no.
el select multiple es provisional, esta mejor la idea de jared(como lo hizo en su pi al form).  Creo que lo mejor seria manejarlo similar/igual que un formulario, es decir seleccionar varios estilos, seleccionar la ciudad y que un button haga la peticion, porque sino por letra que cambias en el input hace una peticion.
=> creo q estan

client/src/app/a-dashboard/profile/page.jsx, client/src/app/auth/page.jsx, client/src/app/page.jsx, client/src/app/redux/features/user/userActions.js, client/src/app/redux/features/user/userSlice.js, client/src/components/header/Header.jsx, client/src/components/nav/Nav.jsx, client/src/components/postDashboard/PostDashboard.jsx, client/src/components/postsDashboard/PostsDashboard.jsx
conectado perfil con back, muestra publicaciones, informacion de perfil, hace log out
=> conexion perfil back

server/index.js, server/src/controllers/filterControllers/getTattooArtistFilteredController.js
Modifiqué el try-catch, porque en el catch no manejaba adecuadamente el error, sino que hacía un console.log()
=> Fix controller

server/index.js, server/src/models/Appointment.js, server/src/models/Review.js, server/src/models/Tattoo.js
agregando columna de fecha y hora de creación del registro (de Publications, de Reviews, de Appointment y de Tattoo)
=> cambios en modelos

client/src/app/explore/page.jsx, client/src/components/filterSideBar/FilterSideBar.jsx
explore page.jsx y FilterSideBar.jsx todo estilado a nuevo con flex y responsive para mantener las propiedades. 
No se toco nada de la funcionalidad, solo el estilado
=> Modificaciones explorer

client/src/app/auth/page.jsx, client/src/app/layout.jsx, client/src/app/redux/features/user/userActions.js, server/src/controllers/loginController/login.js, server/src/controllers/tattooArtistControllers/createTattooArtist.js, server/src/handlers/loginHandler/loginHandler.js, server/src/routes/index.js, server/src/routes/loginRouter.js
Hice el back del login, para que cuando un usuario cree su cuenta, se hashee la contraseña y se guarde hasheada en la base de datos (más seguridad). Luego modifiqué el front para que cuando un usuario intente ingresar con mail registrado, al escribir su contraseña se hashee, se compare con la hasheada guardada en la base de datos y si coincide le de ingreso, si no que muestre los mensajes correspondientes: "Usuario no registrado" o "Contraseña incorrecta"
=> hashear password

server/config/nodemailer.js, server/package-lock.json, server/package.json, server/src/routes/index.js, server/src/routes/nodemailerRouter.js, server/src/utils/nodemailer/confirm-reservation-artist.js, server/src/utils/nodemailer/confirm-reservation-client.js, server/src/utils/nodemailer/delete-publication.js, server/src/utils/nodemailer/delete-user.js, server/src/utils/nodemailer/forget-password.js, server/src/utils/nodemailer/welcome.js
mails de prueba para mandar, funciona todo ok
=> Nodemailer

client/src/app/admin-dashboard/home/createpost/page.jsx, client/src/app/admin-dashboard/home/layout.jsx, client/src/app/admin-dashboard/home/mispublicaciones/page.jsx, client/src/app/admin-dashboard/home/page.jsx, client/src/app/admin-dashboard/layout.jsx, client/src/app/admin-dashboard/page.jsx, client/src/app/admin-dashboard/profile/page.jsx, client/src/app/admin-dashboard/registeredArtists/layout.jsx, client/src/app/admin-dashboard/registeredArtists/page.jsx, client/src/app/redux/features/artists/artistActions.js, client/src/app/redux/features/artists/artistsSlice.js, client/src/components/adminCard/AdminCard.jsx, client/src/components/adminSideBar/AdminSideBar.jsx, client/src/components/admintopBarOptions/AdminTopBarOptions.jsx, client/src/components/filterSideBar/FilterSideBar.jsx
Arrancamos con dash administrador
1-Profile --> ver con team back!
2- artistas registrados --> renderizamos las cards --> falta sumarle el paginado y la ruta dinamica a los posteos
=> Admin dash

client/src/app/redux/features/user/userActions.js, server/src/handlers/loginHandler/loginHandler.js
Cambios en el mensaje de error, el back retorna "User not found" or "Incorrect password" según corresponda, pero al usuario se le muestra "Usuario y/o contraseña incorrectos"
=> cambios en mensaje de error

client/src/app/user-dashboard/home/createpost/page.jsx, client/src/app/user-dashboard/home/layout.jsx, client/src/app/user-dashboard/home/mispublicaciones/page.jsx, client/src/app/user-dashboard/home/page.jsx, client/src/app/user-dashboard/layout.jsx, client/src/app/user-dashboard/page.jsx, client/src/app/user-dashboard/profile/page.jsx, client/src/components/adminCard/AdminCard.jsx, client/src/components/userSideBar/UserSideBar.jsx
=> user dashboard

client/src/app/auth/page.jsx
Se agrega lógica en el login para que detecte si es artista o cliente y lo redirija al dashboard correspondiente
=> Login finalizado

server/src/controllers/publicationControllers/updatePublication.js, server/src/handlers/publicationHandlers/updatePublicationHandler.js
=> Disponibilidad horaria

server/src/controllers/tattooArtistControllers/getTattooArtistById.js, server/src/controllers/tattooArtistControllers/getTattooArtists.js, server/src/models/Publication.js
Cambios en getTattooArtistById y getTattooArtist para que traiga y borre las publicaciones se agrego el id y se modifico el title en el modelo
=> cambios modelos

client/src/app/user-dashboard/page.jsx, client/src/app/utils/ordenarPosts.js, client/src/components/userPostDash/UserPostDash.jsx, client/src/components/userSideBar/UserSideBar.jsx
AL FIN SE VEN LOS POSTEOS DE TODOS LOS ARTISTAS, TIENE EL LINK QUE LLEVA AL DETAILLLLLLLLLLLLL
=> DALEEE USERDASH

server/src/controllers/timeAvailabilityControllers/createTimeAvailability.js, server/src/controllers/timeAvailabilityControllers/getTimeAvailabilityById.js, server/src/controllers/timeAvailabilityControllers/updateTimeAvailability.js, server/src/controllers/timeAvailabilityExceptionControllers/createTimeAvailabilityException.js, server/src/controllers/timeAvailabilityExceptionControllers/getTimeAvailabilityExceptionById.js, server/src/controllers/timeAvailabilityExceptionControllers/updateTimeAvailabilityException.js, server/src/handlers/timeAvailabilityExceptionHandlers/createTimeAvailabilityExceptionHandler.js, server/src/handlers/timeAvailabilityExceptionHandlers/updateTimeAvailabilityExceptionHandler.js, server/src/handlers/timeAvailabilityHandlers/createTimeAvailabilityHandler.js, server/src/handlers/timeAvailabilityHandlers/updateTimeAvailabilityHandler.js, server/src/routes/timeAvailabilityRouter.js
Agregué lógica en el back para que cada tatuador pueda crear una disponibilidad horaria para cada día de la semana sólo una vez y que pueda crear una excepción para una fecha sólo una vez. Si lo quiere modificar tiene que editar (put), no volver a crear (post).
También agregué lógica en el back para no permitir que la finalHour sea menor que la initialHour (tanto en timeAvailability como en exception)
Otro cambio es el los métodos get, ahora hay uno que trae todas las disponibilidades horarias y otro que busca por id de disponiblidad. No está más el que busca por disponibilidad horaria de un tatuador, porque eso ya lo trae el getTattooArtistById
=> cambios disponibilidad y excepciones

client/src/app/admin-dashboard/layout.jsx, client/src/app/admin-dashboard/registeredArtists/page.jsx, client/src/app/admin-dashboard/tattooStyles/page.jsx, client/src/app/redux/features/modalDeleteArtist/modalDeleteArtistAction.js, client/src/app/redux/features/modalDeleteArtist/modalDeleteArtistSlice.js, client/src/app/redux/features/modalDeleteStyle/modalDeleteStyleAction.js, client/src/app/redux/features/modalDeleteStyle/modalDeleteStyleSlice.js, client/src/app/redux/store.js, client/src/app/user-dashboard/profile/page.jsx, client/src/components/adminCard/AdminCard.jsx, client/src/components/admintopBarOptions/AdminTopBarOptions.jsx, client/src/components/modal/ModalDeleteArtist.jsx, client/src/components/modal/ModalDeleteStyle.jsx
modal delete, estilos tattoo y estilos
=> modal delete, estilos tattoo y estilos

client/src/app/user-dashboard/profile/page.jsx
=> Profileeeeeeeee

server/src/controllers/publicationControllers/getPublicationsByArtistId.js
agrego el where : disabled para que en el dashboard del tatuador no aparezcan las publis borradas
=> para que no traiga las eliminadas (probado)

client/src/app/admin-dashboard/registeredArtists/page.jsx, client/src/app/redux/features/artists/artistsSlice.js, client/src/components/adminCard/AdminCard.jsx, client/src/components/admintopBarOptions/AdminTopBarOptions.jsx
vamos de a poco, ordenamientos en el admin dash por nombre del arrtista y card modificada ok.
=> ordenamientos

server/package-lock.json, server/package.json, server/src/controllers/appointmentControllers/createAppointment.js, server/src/handlers/appointmentHandlers/createAppointmentHandler.js, server/src/handlers/mercadoPagoHandlers/createOrder.js, server/src/handlers/mercadoPagoHandlers/successPurchase.js, server/src/models/Appointment.js, server/src/routes/index.js, server/src/routes/mercadoPagoRouter.js
Hice unos pequeños cambios para crear un turno y le agregué a la tabla Appointment la columna depositPrice, que indicaría el monto a pagar para la seña (faltaría hacer esa lógica, una vez que el tatuador pueda cargar su rango de precios por tamaño)
Hice el back para implementar mercado pago, faltaría definir cuáles serían las rutas de redirección en caso que el pago sea aprobado, rechazado, esté pendiente (hice uno muy básico de aprobado que sólo devuelve "Pago aprobado" cuando el cliente apreta el botón "Volver al sitio")
Hay que definir dónde vamos a guardar el id del pago, si le agregamos a la tabla Appointment otra columna o si hacemos otra tabla.
Mañana les muestro cómo funciona, así alguno de ustedes prueba si funciona estando en Argentina
=> pasarela de pagos back

client/src/app/user-dashboard/reservas/page.jsx, client/src/components/bookingCard/BookingCard.jsx
tdv falta ssolucionar un bug del mapeo, esta 90% hecho
=> Cards de resrvas

server/src/controllers/appointmentControllers/createAppointment.js
Agregué la validación para que chequee si ya existe un turno creado en esa fecha y hora con ese tatuador
=> appointment mil validaciones + 1

client/src/app/explore/page.jsx, client/src/app/page.jsx, client/src/components/card/Card.jsx, client/src/components/filterSideBar/FilterSideBar.jsx, client/src/components/nav/Nav.jsx, client/src/components/paginate/Paginate.jsx
Hago responsive del lnading y explore. Falta solucionar un tema con el swiper del explore y el renderizado condicional de los filtros
=> Responsive

client/src/app/auth/layout.jsx, client/src/app/auth/page.jsx
Se edita el form para que quede responsive y agrego boton para volver al inicio
=> form responsive

server/src/controllers/loginController/login.js
Cambio unicamente en el back para que me traida el id del pracerange.
Visto con Pedro.
=> cambio para que me traiga id en el back, visto con pedro

client/src/app/a-dashboard/price/page.jsx, client/src/components/sidebar/SideBar.jsx
listo precios, setear  y  modificar en db
=> precios tatuador

server/src/controllers/appointmentControllers/createAppointment.js
Arreglé el archivo del back createAppointment que no estaban funcionando las validaciones, ahora anda 10 puntos, probé todas las alternativas. 
Les dejo un ejemplo de json que tienen que usar para crear un appointment desde el thunder client por si lo quieren probar:
POST http://localhost:3001/appointments
{
"tattooArtistId": "11978c61-1305-4c83-93d3-b77bda16a825",
"customerId": "8b4e7642-b5ce-4bc7-b557-26cc1567a2b0",
"size": "Pequeño",
"image": "https://www.clara.es/medio/2023/05/22/flor-de-loto-tatuaje-minimalista_249f4752_230522185735_1080x1192.jpg",
"bodyPlace": "Brazo",
"description": "Flor de loto",
"dateAndTime": "2023-12-13T09:00:00.000Z"
}
=> validaciones back appointment funciona

client/src/app/explore/page.jsx
explore se borro la navvvvvvvvvvvvv, y cambio importaciones para el deploy en el explore
=> vuelve navvvvvv

client/src/app/admin-dashboard/layout.jsx, client/src/app/admin-dashboard/registeredArtists/[id]/page.jsx, client/src/app/admin-dashboard/registeredArtists/layout.jsx, client/src/app/admin-dashboard/registeredArtists/page.jsx, client/src/app/auth/page.jsx, client/src/components/adminCard/AdminCard.jsx, client/src/components/adminPostDashboard/AdminPostDashboard.jsx, client/src/components/adminPostsDashboard/AdminPostsDashboard.jsx, client/src/components/modal/ModalDeletePostAdmin.jsx, client/src/components/modal/ModalEditAdmin.jsx, client/src/components/paginateAdmin/PaginateAdmin.jsx, client/tailwind.config.js
Admin-> artistas registrados, ahora si anda el editar publicacion y ell eliminar publicacion + estilos
=> lunes connie vol1

client/src/app/auth/page.jsx, client/src/components/adminSideBar/AdminSideBar.jsx, client/src/components/sidebar/SideBar.jsx, client/src/components/userSideBar/UserSideBar.jsx
Se le agrego la funcionalidad a todos los logout de las sidebar
=> Logout sidebar funcionales

client/src/app/about/page.jsx, client/src/app/explore/[id]/page.jsx, client/src/app/explore/page.jsx
Cambié el tipo de letra en algunos lugares para que manejemos solo tres fuentes. También cambié el mensaje que se le muestra al cliente cuando un tatuador no tiene reseñas. Le puse un poco más de tiempo a las frases que van pasando y las modifiqué un toquecito
=> tipo de letra y mensajes

client/src/app/user-dashboard/profile/page.jsx, client/src/app/user-dashboard/profile/validations.js
VALIDACIONES DEL PERFIL DEL USUARIO
=> velidacionesd del usuario

client/src/app/a-dashboard/calendar/page.jsx, client/src/app/a-dashboard/reviews/page.jsx, client/src/app/admin-dashboard/registeredArtists/page.jsx, client/src/app/admin-dashboard/suspended/page.jsx, client/src/components/ArtistBookingCard/ArtistBookingCard.jsx, client/src/components/ArtistReview/ArtistReview.jsx, client/src/components/admintopBarOptions/AdminTopBarOptions.jsx, client/src/components/header/Header.jsx, client/src/components/starreviews/StarReviews.jsx
arreglo filtros y paginado del admin + estilos de admin, booking card…… y no se que mas
=> miercoles3

client/src/app/auth/page.jsx, client/src/app/user-dashboard/reservas/page.jsx
Saqué el "si no tienes cuenta registrate aquí" que estaba doble y quedaba abajo de "Te damos la bienvenida!"
Cambié el color de los detalles del turno en el dashboard del cliente que no se veían en el mismo color cremita
=> arreglos post demo

client/src/app/a-dashboard/Appointments/page.jsx, client/src/app/a-dashboard/calendar/page.jsx, client/src/app/a-dashboard/home/layout.jsx, client/src/app/a-dashboard/layout.jsx, client/src/app/a-dashboard/price/page.jsx, client/src/app/a-dashboard/profile/page.jsx, client/src/app/a-dashboard/reviews/page.jsx, client/src/app/user-dashboard/layout.jsx, client/src/app/user-dashboard/page.jsx, client/src/app/user-dashboard/profile/page.jsx, client/src/app/user-dashboard/reservas/page.jsx, client/src/components/ArtistBookingCard/ArtistBookingCard.jsx, client/src/components/ArtistReview/ArtistReview.jsx, client/src/components/bookingCard/BookingCard.jsx, client/src/components/postDashboard/PostDashboard.jsx, client/src/components/userPostDash/UserPostDash.jsx
Ya hice responsive el dashboard del artista y del cliente.
Lo único que faltaría es agregar esa sección de "turnos pasados" y "próximos turnos" (por ahora sólo muestra los próximos, si ya pasaron no los muestra)
Además, en el dashboard del cliente en la parte de los turnos, si no sacó ningún turno le aparece como un "explore", eso no está hecho responsive.
=> responsive -> userDashboard y artistDashboard

client/src/app/a-dashboard/Appointments/page.jsx, client/src/app/user-dashboard/reservas/page.jsx, client/src/components/ArtistBookingCard/ArtistBookingCard.jsx, client/src/components/bookingCard/BookingCard.jsx
Ahora se ven los turnos en dos secciones "Próximos turnos" y "Turnos pasados", tanto en el dashboard del artista como del cliente. Si no tiene nigún turno (ni pasado, ni próximo) muestra "No tienes ninguna reserva aún bla bla bla... ". Todo responsive
=> ahora sí se muestran los turnos
